import { expect, test } from '@playwright/test';

test('album cover edits, crops, exports and restores in square and phone formats', async ({ page }, testInfo) => {
  const errors: string[] = [];
  const external: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (!/^(http:\/\/localhost:5173|blob:|data:)/.test(request.url())) external.push(request.url()); });
  await page.goto('/');
  await expect(page.locator('#template')).toBeEnabled();
  await page.locator('#language').selectOption('en');
  // Invalid hidden playback values must never block a cover export.
  await page.locator('#elapsed').fill('oops');
  await page.locator('#template').selectOption('albumCover');
  await expect(page.locator('#cover-format')).toHaveValue('square');
  await expect(page.locator('.lock-guides')).toHaveCount(0);
  await expect(page.locator('#elapsed')).toHaveCount(0);
  const png = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 1200; canvas.height = 1200;
    const ctx = canvas.getContext('2d')!;
    ctx.fillStyle = '#244878'; ctx.fillRect(0, 0, 1200, 400);
    ctx.fillStyle = '#4c8d99'; ctx.fillRect(0, 400, 1200, 400);
    ctx.fillStyle = '#e4a08c'; ctx.fillRect(0, 800, 1200, 400);
    ctx.fillStyle = '#f5ebda'; ctx.beginPath(); ctx.arc(600, 600, 90, 0, Math.PI * 2); ctx.fill();
    return canvas.toDataURL().split(',')[1];
  });
  await page.locator('#photo-upload').setInputFiles({ name: 'cover.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') });
  await expect(page.getByRole('button', { name: 'Download PNG' })).toBeEnabled();
  await page.locator('.swatches button').nth(1).click();
  await expect(page.locator('.swatches button').nth(1)).toHaveAttribute('aria-pressed', 'true');
  await page.locator('#background').fill('#29216a');
  await page.locator('#cover-split').fill('60');
  await page.locator('#zoom').fill('2');
  const photo = page.getByRole('button', { name: 'Move cover image. Use arrow keys to reposition.' });
  await photo.focus(); await photo.press('ArrowDown');
  const cropBefore = await page.locator('.wallpaper canvas').evaluate((node: HTMLCanvasElement) => node.toDataURL());
  await photo.press('ArrowDown');
  await expect.poll(async () => await page.locator('.wallpaper canvas').evaluate((node: HTMLCanvasElement) => node.toDataURL()) !== cropBefore).toBe(true);
  await page.locator('.cover-text-list button').nth(1).click();
  await page.locator('#cover-text').fill('MIDNIGHT\nFEELING');
  await page.locator('#cover-font').selectOption('mono');
  const size = page.getByLabel('Font size', { exact: true });
  await size.fill(''); await size.pressSequentially('22');
  await expect(size).toHaveValue('22');
  await page.getByLabel('Font weight', { exact: true }).fill('700');
  await page.getByLabel('Italic', { exact: true }).check();
  await page.locator('#cover-text-color').fill('#e4a08c');
  await page.getByLabel('Horizontal (%)', { exact: true }).fill('35');
  await page.getByLabel('Vertical (%)', { exact: true }).fill('8');
  await page.getByLabel('Width (%)', { exact: true }).fill('60');
  await page.getByText('Letter & line spacing', { exact: true }).click();
  const spacing = page.getByLabel('Letter spacing', { exact: true });
  await spacing.fill(''); await spacing.pressSequentially('-1.5');
  await expect(spacing).toHaveValue('-1.5');
  await spacing.fill('1.5');
  await page.getByLabel('Line height', { exact: true }).fill('1.6');
  await page.getByRole('button', { name: 'Add text' }).click();
  await page.locator('#cover-text').fill('เพลงของเรา / 私たちの歌');
  await page.locator('#cover-font').selectOption('thai');
  await page.getByLabel('Vertical (%)', { exact: true }).fill('48');
  await page.getByLabel('Width (%)', { exact: true }).fill('90');
  await page.getByLabel('Show text', { exact: true }).uncheck();
  const hidden = await page.locator('.wallpaper canvas').evaluate((node: HTMLCanvasElement) => node.toDataURL());
  await page.getByLabel('Show text', { exact: true }).check();
  await expect.poll(async () => await page.locator('.wallpaper canvas').evaluate((node: HTMLCanvasElement) => node.toDataURL()) !== hidden).toBe(true);
  await page.locator('#language').selectOption('ja');
  await expect(page.locator('#cover-text')).toHaveValue('เพลงของเรา / 私たちの歌');
  await page.locator('#language').selectOption('en');
  await expect(page.getByRole('status').first()).toContainText('Saved on this device');
  await page.reload();
  await expect(page.locator('#template')).toHaveValue('albumCover');
  await expect(page.locator('#cover-split')).toHaveValue('60');
  await expect(page.locator('#background')).toHaveValue('#29216a');
  await expect(page.locator('#zoom')).toHaveValue('2');
  await expect(page.locator('.cover-text-list button')).toHaveCount(5);
  await page.locator('.cover-text-list button').nth(1).click();
  await expect(page.locator('#cover-text')).toHaveValue('MIDNIGHT\nFEELING');
  await expect(page.locator('#cover-font')).toHaveValue('mono');
  await expect(page.getByLabel('Font size', { exact: true })).toHaveValue('22');
  await expect(page.getByLabel('Italic', { exact: true })).toBeChecked();
  await page.locator('.workspace').screenshot({ path: testInfo.outputPath('album-cover-preview.png') });
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download PNG' }).click(); await download;
  await expect(page.locator('.download-result a')).toBeVisible();
  const exported = await page.evaluate(async () => {
    const image = new Image(); image.src = document.querySelector<HTMLAnchorElement>('.download-result a')!.href; await image.decode();
    const canvas = document.createElement('canvas'); canvas.width = image.width; canvas.height = image.height;
    const ctx = canvas.getContext('2d')!; ctx.drawImage(image, 0, 0);
    const sample = (y: number) => Array.from(ctx.getImageData(1, y, 1, 1).data).slice(0, 3);
    const preview = document.querySelector<HTMLCanvasElement>('.wallpaper canvas')!;
    return { width: image.width, height: image.height, top: sample(10), beforeSplit: sample(1430), belowSplit: sample(1450), previewWidth: preview.width, previewHeight: preview.height };
  });
  expect(exported).toMatchObject({ width: 2400, height: 2400, top: [41, 33, 106], beforeSplit: [41, 33, 106], previewWidth: 940, previewHeight: 940 });
  expect(exported.belowSplit).not.toEqual([41, 33, 106]);
  await page.locator('#cover-format').selectOption('phone');
  await page.locator('#device').selectOption('iPhone 12 mini');
  await expect(page.locator('.lock-guides')).toHaveCount(1);
  const phoneDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download PNG' }).click(); await phoneDownload;
  await expect(page.locator('.download-result a')).toBeVisible();
  expect(await page.evaluate(async () => {
    const image = new Image(); image.src = document.querySelector<HTMLAnchorElement>('.download-result a')!.href; await image.decode(); return [image.width, image.height];
  })).toEqual([1080, 2340]);
  await page.locator('.cover-text-list button').last().click();
  await page.getByRole('button', { name: 'Delete text' }).click();
  await expect(page.locator('.cover-text-list button')).toHaveCount(4);
  await page.locator('#template').selectOption('custom');
  await expect(page.locator('#elapsed')).toHaveValue('oops');
  await expect(page.getByRole('button', { name: 'Download PNG' })).toBeDisabled();
  expect(errors).toEqual([]); expect(external).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
