import { revealInspector, expandInspector } from './inspector';
import { expect, test } from '@playwright/test';

test('Polaroid presets preserve content and custom tilted cards survive reload and export', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.locator('#template')).toBeEnabled();
  await revealInspector(page.locator('#language')); await page.locator('#language').selectOption('en');
  await revealInspector(page.locator('#template')); await page.locator('#template').selectOption('polaroid');
  const imageData = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 1200; canvas.height = 900;
    const context = canvas.getContext('2d')!;
    const gradient = context.createLinearGradient(0, 0, 0, 900); gradient.addColorStop(0, '#658c9c'); gradient.addColorStop(1, '#e9b8a0');
    context.fillStyle = gradient; context.fillRect(0, 0, 1200, 900);
    context.fillStyle = '#f6e5b8'; context.beginPath(); context.arc(830, 250, 95, 0, Math.PI * 2); context.fill();
    context.fillStyle = '#465b68'; context.beginPath(); context.moveTo(0, 720); context.lineTo(310, 460); context.lineTo(750, 900); context.lineTo(0, 900); context.fill();
    return canvas.toDataURL().split(',')[1];
  });
  await page.locator('#photo-upload').setInputFiles({ name: 'memory.png', mimeType: 'image/png', buffer: Buffer.from(imageData, 'base64') });
  await expect(page.getByRole('button', { name: 'Download PNG' })).toBeEnabled();
  await revealInspector(page.locator('#title')); await page.locator('#title').fill('夕暮れの記憶'); await revealInspector(page.locator('#artist')); await page.locator('#artist').fill('Our little memory');
  await revealInspector(page.locator('#background')); await page.locator('#background').fill('#d7dfd9');
  await page.getByRole('switch', { includeHidden: true, name: 'Lock Screen preview', exact: true }).uncheck();
  for (const preset of ['Classic', 'Clean', 'Diary', 'Cinema', 'Noir']) {
    await page.getByRole('button', { name: new RegExp(`^${preset} `) }).click();
    await expect(page.getByRole('button', { name: new RegExp(`^${preset} `) })).toHaveAttribute('aria-pressed', 'true');
    await expect(page.locator('#title')).toHaveValue('夕暮れの記憶');
    await expect(page.locator('#background')).toHaveValue('#d7dfd9');
    await expect(page.locator('#zoom')).toHaveValue('1');
    await expect(page.getByRole('status').first()).toHaveText('Saved on this device');
    await page.locator('.wallpaper').screenshot({ path: testInfo.outputPath(`${preset}.png`) });
  }
  await page.getByRole('button', { name: /^Diary / }).click();
  await expandInspector(page, 'Paper frame & layout');
  await revealInspector(page.getByLabel('Photo aspect ratio', { exact: true })); await page.getByLabel('Photo aspect ratio', { exact: true }).selectOption('portrait');
  await revealInspector(page.getByLabel('Card rotation', { exact: true })); await page.getByLabel('Card rotation', { exact: true }).fill('8');
  await revealInspector(page.getByLabel('Paper border width', { exact: true })); await page.getByLabel('Paper border width', { exact: true }).fill('28');
  await revealInspector(page.getByLabel('Paper color', { exact: true })); await page.getByLabel('Paper color', { exact: true }).fill('#f4d4ba');
  await revealInspector(page.getByLabel('Paper ink color', { exact: true })); await page.getByLabel('Paper ink color', { exact: true }).fill('#402e38');
  await expandInspector(page, 'Fonts & text colors');
  const title = page.getByRole('group', { includeHidden: true, name: 'Song title / text', exact: true });
  await revealInspector(title.getByLabel('Font', { exact: true })); await title.getByLabel('Font', { exact: true }).selectOption('japanese');
  await revealInspector(title.getByLabel('Font size', { exact: true })); await title.getByLabel('Font size', { exact: true }).fill('28');
  await expandInspector(page, 'Tape, notes & details');
  await revealInspector(page.getByLabel('Decorative tape', { exact: true })); await page.getByLabel('Decorative tape', { exact: true }).selectOption('corners');
  await revealInspector(page.getByLabel('Date / note text', { exact: true })); await page.getByLabel('Date / note text', { exact: true }).fill('2026.09.12 / ความทรงจำ');
  await revealInspector(page.locator('#zoom')); await page.locator('#zoom').fill('2');
  const art = page.locator('.artwork-hit');
  await art.scrollIntoViewIfNeeded();
  const rect = (await art.boundingBox())!;
  await page.mouse.move(rect.x + rect.width / 2, rect.y + rect.height / 2);
  await page.mouse.down(); await page.mouse.move(rect.x + rect.width / 2 + 24, rect.y + rect.height / 2 + 4, { steps: 4 }); await page.mouse.up();
  await expect(page.getByRole('status').first()).toHaveText('Saved on this device');
  const saved = await page.evaluate(async () => {
    const path = '/src/storage.ts'; const { loadDraft } = await import(path); return await loadDraft();
  });
  expect(saved.crop.x).toBeLessThan(0.5);
  expect(saved.crop.y).toBeCloseTo(0.5, 1);
  await page.reload();
  await expect(page.locator('#template')).toHaveValue('polaroid');
  await expandInspector(page, 'Paper frame & layout');
  await expect(page.getByLabel('Card rotation', { exact: true })).toHaveValue('8');
  await expect(page.getByLabel('Photo aspect ratio', { exact: true })).toHaveValue('portrait');
  await expect(page.getByLabel('Paper color', { exact: true })).toHaveValue('#f4d4ba');
  await expandInspector(page, 'Tape, notes & details');
  await expect(page.getByLabel('Date / note text', { exact: true })).toHaveValue('2026.09.12 / ความทรงจำ');
  await expect(page.getByLabel('Decorative tape', { exact: true })).toHaveValue('corners');
  await revealInspector(page.locator('#elapsed')); await page.locator('#elapsed').fill('bad');
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download PNG' }).click(); await download;
  await expect(page.locator('.download-result a')).toBeVisible();
  const pixels = await page.evaluate(async () => {
    const storagePath = '/src/storage.ts', layoutPath = '/src/polaroid.ts';
    const { loadDraft } = await import(storagePath), { polaroidLayout } = await import(layoutPath);
    const draft = await loadDraft();
    const img = new Image(); img.src = document.querySelector<HTMLAnchorElement>('.download-result a')!.href; await img.decode();
    const canvas = document.createElement('canvas'); canvas.width = img.width; canvas.height = img.height;
    const context = canvas.getContext('2d')!; context.drawImage(img, 0, 0);
    const frame = polaroidLayout(470 * img.height / img.width, draft.polaroid, draft.showPalette);
    const x = draft.polaroid.padding / 2 - frame.cardWidth / 2, y = draft.polaroid.padding + frame.photoHeight / 2 - frame.cardHeight / 2;
    const px = (frame.centerX + (x * Math.cos(frame.angle) - y * Math.sin(frame.angle)) * frame.scale) * img.width / 470;
    const py = (frame.centerY + (x * Math.sin(frame.angle) + y * Math.cos(frame.angle)) * frame.scale) * img.width / 470;
    return { width: img.width, height: img.height, paper: [...context.getImageData(Math.round(px), Math.round(py), 1, 1).data].slice(0, 3) };
  });
  expect(pixels).toEqual({ width: 1179, height: 2556, paper: [244, 212, 186] });
  await page.locator('.wallpaper').screenshot({ path: testInfo.outputPath('custom-diary.png') });
  await page.getByRole('switch', { includeHidden: true, name: 'Show progress bar', exact: true }).check();
  await expect(page.getByRole('button', { name: 'Download PNG' })).toBeDisabled();
  await page.getByRole('button', { name: /^Clean / }).click();
  await page.getByRole('button', { name: /^Diary / }).click();
  await expect(page.getByLabel('Date / note text', { exact: true })).toHaveValue('2026.09.12 / ความทรงจำ');
  await revealInspector(page.locator('#template')); await page.locator('#template').selectOption('custom'); await revealInspector(page.locator('#template')); await page.locator('#template').selectOption('polaroid');
  await revealInspector(page.locator('#language')); await page.locator('#language').selectOption('ja');
  await expect(page.locator('#title')).toHaveValue('夕暮れの記憶');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
